[project]
name = "msdl-jci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jordan Ferdinand", email = "253198146+jordan-ferdinand_IMSI@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4==4.15.0",
    "feedparser>=6.0.14",
    "httpx==1.0.dev3",
    "numpy>=1.26.0",
    "pandas>=2.2.0",
    "pandas-stubs~=3.0.5",
    "psycopg2-binary>=2.9.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "python-dotenv>=1.0.0",
    "scikit-learn>=1.4.0",
    "sqlalchemy>=2.0.0",
    "yfinance>=0.2.0",
]

[project.scripts]
msdl-jci = "msdl_jci:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
